export const ActionTypes = {
  SERVER_NOT_REPLY: 'SERVER_NOT_REPLY',
  SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_IN_SUCCESSED: 'SIGN_IN_SUCCESSED',
  SIGN_UP_SUCCESSED: 'SIGN_UP_SUCCESSED',
  SIGN_IN_FAILED: 'SIGN_IN_FAILED',
  SIGN_UP_FAILED: 'SIGN_UP_FAILED',
  PRODUCT_REQUEST: 'PRODUCT_REQUEST',
  PRODUCT_SUCCESSED: 'PRODUCT_SUCCESSED',
  PRODUCT_FAILED: 'PRODUCT_FAILED',
}